# Generated by Django 4.1.6 on 2023-02-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_source',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default=None),
        ),
    ]
